apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app

resources:
  - guardrails.yaml
  - default-deny.yaml
  - admission-policy.yaml

commonLabels:
  app.kubernetes.io/part-of: cage

