#!/usr/bin/env python3
"""
bio_signal_infra.py — Biological Signal Infrastructure
Governance layer for physiological signals fed into the LLM governance mesh.

Core principle: biological signals are the hardest channel to fabricate because
they are generated by physical systems — the cardiovascular, galvanic, and neural
systems — that are not under direct voluntary control.  Biosignal governance
converts physiological authenticity evidence into binding elevation for human-
presence claims.

Theoretical foundations:
  Berger (1929)           — electroencephalography (EEG): neural oscillation patterns
  Fere (1888)             — galvanic skin response (GSR) as arousal measure
  Task Force (1996)       — heart rate variability (HRV): standards of measurement
  Kahneman (1973)         — pupil dilation as cognitive load proxy
  Cacioppo & Petty (1983) — electromyography (EMG) as emotion-processing signal
  Porges (1995)           — polyvagal theory: autonomic nervous system governance

Biosignal taxonomy:
  PHYSIOLOGICAL_AUTHENTIC     — all channels within normal human range (severity 0)
  HRV_ANOMALY                 — HRV outside normal range (severity 2)
  GSR_FLATLINE                — GSR shows no variance (liveness failure) (severity 3)
  EEG_SYNC_ANOMALY            — EEG shows abnormal inter-channel synchrony (severity 2)
  LIVENESS_FAILURE            — no physiological activity detected (replay/synthetic) (severity 3)
  DECEPTION_SIGNAL            — multi-channel pattern consistent with deceptive arousal (severity 2)
  CHANNEL_MISMATCH            — channels from different physiological states (severity 3)

Binding by verification:
  5 — all channels present, within norms, hardware-attested, anti-replay passed
  4 — all channels present, within norms, hardware-attested
  3 — all channels within norms, no attestation
  2 — minor anomaly (HRV / EEG sync / deception signal)
  1 — GSR flatline, liveness failure, or channel mismatch
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, FrozenSet, List, Optional, Sequence, Tuple
from governance_core import TestRunner


# ─── constants ────────────────────────────────────────────────────────────────

_BINDING_MIN: int = 1
_BINDING_MAX: int = 5
_HIGH_SEVERITY: int = 3
_COMPROMISED_REJECTED: int = 3
_COMPROMISED_HIGH_SEV: int = 3

# HRV norms (Task Force 1996)
_HRV_RMSSD_MIN: float = 15.0    # ms — below this is clinically low (but > 5 = alive)
_HRV_RMSSD_MAX: float = 120.0   # ms — above this is clinically high
_HRV_RMSSD_LIVENESS: float = 5.0 # ms — below this → liveness failure

# Heart rate norms
_HR_MIN_BPM: float = 30.0
_HR_MAX_BPM: float = 220.0

# GSR norms
_GSR_VARIANCE_LIVENESS: float = 0.001  # µS² — below this → flatline

# EEG coherence (inter-channel synchrony)
_EEG_SYNC_HIGH: float = 0.95   # > this → pathological synchrony (seizure-like)
_EEG_SYNC_LOW: float = 0.05    # < this → implausibly decorrelated

# Multi-channel deception: all channels simultaneously elevated
_DECEPTION_CHANNEL_THRESHOLD: int = 3   # ≥ this many channels elevated → flag


# ─── enums ────────────────────────────────────────────────────────────────────

class BioThreat(Enum):
    PHYSIOLOGICAL_AUTHENTIC = "PHYSIOLOGICAL_AUTHENTIC"
    HRV_ANOMALY             = "HRV_ANOMALY"
    GSR_FLATLINE            = "GSR_FLATLINE"
    EEG_SYNC_ANOMALY        = "EEG_SYNC_ANOMALY"
    LIVENESS_FAILURE        = "LIVENESS_FAILURE"
    DECEPTION_SIGNAL        = "DECEPTION_SIGNAL"
    CHANNEL_MISMATCH        = "CHANNEL_MISMATCH"


class BioVerdict(Enum):
    TRUSTED     = "TRUSTED"
    PROVISIONAL = "PROVISIONAL"
    SUSPECT     = "SUSPECT"
    REJECTED    = "REJECTED"


class BioSurfaceVerdict(Enum):
    SURFACE_CLEAN        = "SURFACE_CLEAN"
    SURFACE_DEGRADED     = "SURFACE_DEGRADED"
    SURFACE_CONTAMINATED = "SURFACE_CONTAMINATED"
    SURFACE_COMPROMISED  = "SURFACE_COMPROMISED"


# ─── tables ───────────────────────────────────────────────────────────────────

_THREAT_SEVERITY: Dict[BioThreat, int] = {
    BioThreat.PHYSIOLOGICAL_AUTHENTIC: 0,
    BioThreat.HRV_ANOMALY:             2,
    BioThreat.EEG_SYNC_ANOMALY:        2,
    BioThreat.DECEPTION_SIGNAL:        2,
    BioThreat.GSR_FLATLINE:            3,
    BioThreat.LIVENESS_FAILURE:        3,
    BioThreat.CHANNEL_MISMATCH:        3,
}

_VERDICT_GOVERNANCE: Dict[BioVerdict, str] = {
    BioVerdict.TRUSTED:     "AFFIRM",
    BioVerdict.PROVISIONAL: "SCRUTINISE",
    BioVerdict.SUSPECT:     "WITHHOLD",
    BioVerdict.REJECTED:    "VOID",
}


# ─── dataclasses ──────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class BioSignal:
    """
    A multi-channel physiological recording session.

    hrv_rmssd_ms:       HRV root mean square of successive differences (ms).
    heart_rate_bpm:     mean heart rate (beats per minute).
    gsr_variance_us2:   GSR signal variance (µS²).
    eeg_mean_coherence: mean inter-channel EEG coherence [0, 1].
    elevated_channels:  count of channels showing simultaneous stress elevation.
    hardware_attested:  True if wearable/device guarantees signal integrity.
    anti_replay_passed: True if liveness challenge was successfully answered.
    channel_count:      number of physiological channels present.
    """
    signal_id:          str
    hrv_rmssd_ms:       float
    heart_rate_bpm:     float
    gsr_variance_us2:   float
    eeg_mean_coherence: float       # 0 = decorrelated, 1 = fully synchronised
    elevated_channels:  int = 0
    hardware_attested:  bool = False
    anti_replay_passed: bool = False
    channel_count:      int = 3


@dataclass(frozen=True)
class BioDecision:
    signal_id:         str
    threats:           Tuple[BioThreat, ...]
    binding_level:     int
    verdict:           BioVerdict
    governance_action: str
    reason:            str
    liveness_score:    float    # 0 = dead / synthetic, 1 = fully alive


@dataclass(frozen=True)
class BioSurfaceAudit:
    total_signals:       int
    trusted:             int
    provisional:         int
    suspect:             int
    rejected:            int
    threat_distribution: Dict[str, int]
    surface_verdict:     BioSurfaceVerdict
    high_severity_count: int


# ─── private helpers ──────────────────────────────────────────────────────────

def _liveness_score(sig: BioSignal) -> float:
    """Composite liveness score [0, 1] from all channels."""
    scores = []
    # HRV component
    hrv_score = min(sig.hrv_rmssd_ms / _HRV_RMSSD_MIN, 1.0) if sig.hrv_rmssd_ms > 0 else 0.0
    scores.append(hrv_score)
    # HR component (in-range)
    hr_score = 1.0 if _HR_MIN_BPM <= sig.heart_rate_bpm <= _HR_MAX_BPM else 0.0
    scores.append(hr_score)
    # GSR component
    gsr_score = 1.0 if sig.gsr_variance_us2 > _GSR_VARIANCE_LIVENESS else 0.0
    scores.append(gsr_score)
    return sum(scores) / len(scores)


def _detect_bio_threats(sig: BioSignal) -> List[BioThreat]:
    threats: List[BioThreat] = []

    # Liveness failure: HRV too low OR HR out of range
    if (sig.hrv_rmssd_ms < _HRV_RMSSD_LIVENESS
            or not (_HR_MIN_BPM <= sig.heart_rate_bpm <= _HR_MAX_BPM)):
        threats.append(BioThreat.LIVENESS_FAILURE)

    # GSR flatline
    if sig.gsr_variance_us2 < _GSR_VARIANCE_LIVENESS:
        threats.append(BioThreat.GSR_FLATLINE)

    # HRV anomaly (alive but outside clinical norms)
    if (BioThreat.LIVENESS_FAILURE not in threats
            and not (_HRV_RMSSD_MIN <= sig.hrv_rmssd_ms <= _HRV_RMSSD_MAX)):
        threats.append(BioThreat.HRV_ANOMALY)

    # EEG synchrony anomaly
    if (sig.eeg_mean_coherence > _EEG_SYNC_HIGH
            or sig.eeg_mean_coherence < _EEG_SYNC_LOW):
        threats.append(BioThreat.EEG_SYNC_ANOMALY)

    # Deception signal: multiple channels simultaneously elevated
    if sig.elevated_channels >= _DECEPTION_CHANNEL_THRESHOLD:
        threats.append(BioThreat.DECEPTION_SIGNAL)

    # Channel mismatch: channel_count too low to validate
    if sig.channel_count < 2 and not threats:
        # Single channel with no other issues → treat as provisional,
        # but if combined with another anomaly → mismatch
        pass
    if sig.channel_count < 1:
        threats.append(BioThreat.CHANNEL_MISMATCH)

    return threats


def _compute_binding(sig: BioSignal, threats: List[BioThreat]) -> int:
    max_sev = max((_THREAT_SEVERITY[t] for t in threats), default=0)
    if max_sev >= _HIGH_SEVERITY:
        return 1
    if max_sev == 2:
        return 2
    if sig.hardware_attested and sig.anti_replay_passed:
        return 5
    if sig.hardware_attested:
        return 4
    if not threats:
        return 3
    return 2


# ─── public API ───────────────────────────────────────────────────────────────

def evaluate_bio(signal: BioSignal) -> BioDecision:
    """
    Evaluate a BioSignal for governance.

    Decision priority:
      1. High-severity threat (≥ 3)  → REJECTED
      2. Medium-severity threat (= 2) → SUSPECT
      3. No threats, binding ≥ 4     → TRUSTED
      4. No threats, binding 2–3     → PROVISIONAL
    """
    threats = _detect_bio_threats(signal)
    binding = _compute_binding(signal, threats)
    liveness = _liveness_score(signal)

    if not threats:
        threats = [BioThreat.PHYSIOLOGICAL_AUTHENTIC]

    max_sev = max(_THREAT_SEVERITY[t] for t in threats)

    if max_sev >= _HIGH_SEVERITY:
        verdict = BioVerdict.REJECTED
        reason = f"Physiological integrity failure: {[t.value for t in threats if _THREAT_SEVERITY[t] >= _HIGH_SEVERITY]}"
    elif max_sev == 2:
        verdict = BioVerdict.SUSPECT
        reason = f"Biosignal anomaly: {[t.value for t in threats if _THREAT_SEVERITY[t] == 2]}"
    elif binding >= 4:
        verdict = BioVerdict.TRUSTED
        reason = f"Physiologically authentic; binding={binding}"
    else:
        verdict = BioVerdict.PROVISIONAL
        reason = f"Within normal range; binding={binding}"

    return BioDecision(
        signal_id=signal.signal_id,
        threats=tuple(threats),
        binding_level=binding,
        verdict=verdict,
        governance_action=_VERDICT_GOVERNANCE[verdict],
        reason=reason,
        liveness_score=liveness,
    )


def audit_bio_surface(signals: Sequence[BioSignal]) -> BioSurfaceAudit:
    """Aggregate governance report for a collection of BioSignals."""
    if not signals:
        return BioSurfaceAudit(
            total_signals=0, trusted=0, provisional=0, suspect=0, rejected=0,
            threat_distribution={t.value: 0 for t in BioThreat},
            surface_verdict=BioSurfaceVerdict.SURFACE_CLEAN,
            high_severity_count=0,
        )

    decisions = [evaluate_bio(s) for s in signals]
    trusted     = sum(1 for d in decisions if d.verdict == BioVerdict.TRUSTED)
    provisional = sum(1 for d in decisions if d.verdict == BioVerdict.PROVISIONAL)
    suspect     = sum(1 for d in decisions if d.verdict == BioVerdict.SUSPECT)
    rejected    = sum(1 for d in decisions if d.verdict == BioVerdict.REJECTED)

    dist: Dict[str, int] = {t.value: 0 for t in BioThreat}
    for d in decisions:
        for t in d.threats:
            dist[t.value] += 1

    high_sev = sum(
        1 for d in decisions
        if any(_THREAT_SEVERITY[t] >= _HIGH_SEVERITY for t in d.threats)
    )

    if rejected >= _COMPROMISED_REJECTED or high_sev >= _COMPROMISED_HIGH_SEV:
        sv = BioSurfaceVerdict.SURFACE_COMPROMISED
    elif rejected >= 1 or high_sev >= 1:
        sv = BioSurfaceVerdict.SURFACE_CONTAMINATED
    elif suspect > 0 or provisional > 0:
        sv = BioSurfaceVerdict.SURFACE_DEGRADED
    else:
        sv = BioSurfaceVerdict.SURFACE_CLEAN

    return BioSurfaceAudit(
        total_signals=len(decisions),
        trusted=trusted, provisional=provisional,
        suspect=suspect, rejected=rejected,
        threat_distribution=dist,
        surface_verdict=sv,
        high_severity_count=high_sev,
    )


# ─── test suite ───────────────────────────────────────────────────────────────

def _sig(sid: str, **kw) -> BioSignal:
    defaults = dict(
        hrv_rmssd_ms=45.0,
        heart_rate_bpm=70.0,
        gsr_variance_us2=0.5,
        eeg_mean_coherence=0.5,
        elevated_channels=0,
        hardware_attested=False,
        anti_replay_passed=False,
        channel_count=3,
    )
    defaults.update(kw)
    return BioSignal(signal_id=sid, **defaults)


def _run_tests() -> None:
    tr = TestRunner('bio_signal_infra.py — Test Suite', verbose=False)
    tr.header()

    # ── Group A: trusted / clean ──────────────────────────────────────────────
    d = evaluate_bio(_sig("A01", hardware_attested=True, anti_replay_passed=True))
    tr.expect("UT-A01: hw+anti-replay → TRUSTED, bind=5", d.verdict, BioVerdict.TRUSTED)
    tr.expect("UT-A01b: binding == 5",                     d.binding_level, 5)
    tr.expect("UT-A01c: AFFIRM",                            d.governance_action, "AFFIRM")
    tr.expect("UT-A01d: PHYSIOLOGICAL_AUTHENTIC in threats",
          BioThreat.PHYSIOLOGICAL_AUTHENTIC in d.threats, True)

    d = evaluate_bio(_sig("A02", hardware_attested=True))
    tr.expect("UT-A02: hw only → TRUSTED, bind=4", d.verdict, BioVerdict.TRUSTED)
    tr.expect("UT-A02b: binding == 4",              d.binding_level, 4)

    d = evaluate_bio(_sig("A03"))
    tr.expect("UT-A03: no hw → PROVISIONAL, bind=3", d.verdict, BioVerdict.PROVISIONAL)
    tr.expect("UT-A03b: binding == 3",               d.binding_level, 3)

    # ── Group B: liveness failure ─────────────────────────────────────────────
    d = evaluate_bio(_sig("B01", hrv_rmssd_ms=1.0))   # HRV < 5ms
    tr.expect("UT-B01: HRV < 5ms → LIVENESS_FAILURE",
          BioThreat.LIVENESS_FAILURE in d.threats, True)
    tr.expect("UT-B01b: REJECTED", d.verdict, BioVerdict.REJECTED)
    tr.expect("UT-B01c: VOID",     d.governance_action, "VOID")
    tr.expect("UT-B01d: binding=1", d.binding_level, 1)

    d = evaluate_bio(_sig("B02", heart_rate_bpm=300.0))
    tr.expect("UT-B02: HR=300bpm → LIVENESS_FAILURE",
          BioThreat.LIVENESS_FAILURE in d.threats, True)

    d = evaluate_bio(_sig("B03", heart_rate_bpm=10.0))
    tr.expect("UT-B03: HR=10bpm → LIVENESS_FAILURE",
          BioThreat.LIVENESS_FAILURE in d.threats, True)

    # ── Group C: GSR flatline ─────────────────────────────────────────────────
    d = evaluate_bio(_sig("C01", gsr_variance_us2=0.0))
    tr.expect("UT-C01: GSR flatline → GSR_FLATLINE",
          BioThreat.GSR_FLATLINE in d.threats, True)
    tr.expect("UT-C01b: REJECTED", d.verdict, BioVerdict.REJECTED)

    d = evaluate_bio(_sig("C02", gsr_variance_us2=0.01))
    tr.expect("UT-C02: GSR active → no GSR_FLATLINE",
          BioThreat.GSR_FLATLINE in d.threats, False)

    # ── Group D: HRV anomaly (alive but out of clinical range) ────────────────
    d = evaluate_bio(_sig("D01", hrv_rmssd_ms=200.0))   # above max, but alive
    tr.expect("UT-D01: HRV=200ms → HRV_ANOMALY",
          BioThreat.HRV_ANOMALY in d.threats, True)
    tr.expect("UT-D01b: SUSPECT",    d.verdict, BioVerdict.SUSPECT)
    tr.expect("UT-D01c: WITHHOLD",   d.governance_action, "WITHHOLD")

    d = evaluate_bio(_sig("D02", hrv_rmssd_ms=8.0))   # low but above liveness threshold
    tr.expect("UT-D02: HRV=8ms → HRV_ANOMALY (low)",
          BioThreat.HRV_ANOMALY in d.threats, True)

    d = evaluate_bio(_sig("D03", hrv_rmssd_ms=60.0))   # within normal
    tr.expect("UT-D03: HRV=60ms → no HRV_ANOMALY",
          BioThreat.HRV_ANOMALY in d.threats, False)

    # ── Group E: EEG synchrony ────────────────────────────────────────────────
    d = evaluate_bio(_sig("E01", eeg_mean_coherence=0.98))
    tr.expect("UT-E01: EEG coherence=0.98 → EEG_SYNC_ANOMALY (too high)",
          BioThreat.EEG_SYNC_ANOMALY in d.threats, True)

    d = evaluate_bio(_sig("E02", eeg_mean_coherence=0.02))
    tr.expect("UT-E02: EEG coherence=0.02 → EEG_SYNC_ANOMALY (too low)",
          BioThreat.EEG_SYNC_ANOMALY in d.threats, True)

    d = evaluate_bio(_sig("E03", eeg_mean_coherence=0.5))
    tr.expect("UT-E03: EEG coherence=0.5 → no anomaly",
          BioThreat.EEG_SYNC_ANOMALY in d.threats, False)

    # ── Group F: deception signal ─────────────────────────────────────────────
    d = evaluate_bio(_sig("F01", elevated_channels=3))
    tr.expect("UT-F01: 3 elevated channels → DECEPTION_SIGNAL",
          BioThreat.DECEPTION_SIGNAL in d.threats, True)
    tr.expect("UT-F01b: SUSPECT", d.verdict, BioVerdict.SUSPECT)

    d = evaluate_bio(_sig("F02", elevated_channels=2))
    tr.expect("UT-F02: 2 elevated channels → no DECEPTION_SIGNAL",
          BioThreat.DECEPTION_SIGNAL in d.threats, False)

    # ── Group G: liveness_score ───────────────────────────────────────────────
    d_alive = evaluate_bio(_sig("G01"))
    d_dead  = evaluate_bio(_sig("G02", hrv_rmssd_ms=0.0, heart_rate_bpm=0.0, gsr_variance_us2=0.0))
    tr.expect("UT-G01: liveness_score(alive) > liveness_score(dead)",
          d_alive.liveness_score > d_dead.liveness_score, True)

    # ── Group H: audit surface ────────────────────────────────────────────────
    clean = [_sig(f"H{i}", hardware_attested=True, anti_replay_passed=True) for i in range(5)]
    audit = audit_bio_surface(clean)
    tr.expect("UT-H01: all trusted → SURFACE_CLEAN",  audit.surface_verdict, BioSurfaceVerdict.SURFACE_CLEAN)
    tr.expect("UT-H02: trusted == 5",                  audit.trusted, 5)

    one_rejected = [
        _sig("H10", hardware_attested=True, anti_replay_passed=True),
        _sig("H11", hrv_rmssd_ms=0.0),
    ]
    audit = audit_bio_surface(one_rejected)
    tr.expect("UT-H03: 1 rejected → CONTAMINATED",
          audit.surface_verdict, BioSurfaceVerdict.SURFACE_CONTAMINATED)

    three_rejected = [_sig(f"H2{i}", hrv_rmssd_ms=0.0) for i in range(3)]
    audit = audit_bio_surface(three_rejected)
    tr.expect("UT-H04: 3 rejected → COMPROMISED",
          audit.surface_verdict, BioSurfaceVerdict.SURFACE_COMPROMISED)

    empty = audit_bio_surface([])
    tr.expect("UT-H05: empty → SURFACE_CLEAN", empty.surface_verdict, BioSurfaceVerdict.SURFACE_CLEAN)

    # ── Stress tests ──────────────────────────────────────────────────────────

    # ST-01: 1000 healthy attested signals → all TRUSTED, SURFACE_CLEAN
    st1 = [_sig(f"s1_{i}", hardware_attested=True, anti_replay_passed=True) for i in range(1000)]
    a1 = audit_bio_surface(st1)
    tr.expect("ST-01: 1000 clean → SURFACE_CLEAN", a1.surface_verdict, BioSurfaceVerdict.SURFACE_CLEAN)
    tr.expect("ST-01b: trusted == 1000",            a1.trusted, 1000)

    # ST-02: 500 flatline signals → all REJECTED, COMPROMISED
    st2 = [_sig(f"s2_{i}", gsr_variance_us2=0.0) for i in range(500)]
    a2 = audit_bio_surface(st2)
    tr.expect("ST-02: 500 flatline → SURFACE_COMPROMISED",
          a2.surface_verdict, BioSurfaceVerdict.SURFACE_COMPROMISED)
    tr.expect("ST-02b: rejected == 500", a2.rejected, 500)

    # ST-03: 800 healthy + 200 liveness failure
    st3 = (
        [_sig(f"s3a{i}", hardware_attested=True, anti_replay_passed=True) for i in range(800)]
        + [_sig(f"s3b{i}", hrv_rmssd_ms=0.0) for i in range(200)]
    )
    a3 = audit_bio_surface(st3)
    tr.expect("ST-03: 200 liveness failure → COMPROMISED",
          a3.surface_verdict, BioSurfaceVerdict.SURFACE_COMPROMISED)
    tr.expect("ST-03b: trusted == 800",  a3.trusted, 800)
    tr.expect("ST-03c: rejected == 200", a3.rejected, 200)

    # ST-04: EEG sync anomaly flood → all SUSPECT
    st4 = [_sig(f"s4_{i}", eeg_mean_coherence=0.99) for i in range(300)]
    a4 = audit_bio_surface(st4)
    tr.expect("ST-04: 300 EEG sync anomaly → all SUSPECT", a4.suspect, 300)
    tr.expect("ST-04b: SURFACE_DEGRADED", a4.surface_verdict, BioSurfaceVerdict.SURFACE_DEGRADED)

    # ST-05: deception signal mass → all SUSPECT
    st5 = [_sig(f"s5_{i}", elevated_channels=5) for i in range(200)]
    a5 = audit_bio_surface(st5)
    tr.expect("ST-05: 200 deception signals → all SUSPECT", a5.suspect, 200)
    tr.expect("ST-05b: SURFACE_DEGRADED", a5.surface_verdict, BioSurfaceVerdict.SURFACE_DEGRADED)

    # ST-06: 2 rejected → CONTAMINATED
    st6 = [_sig(f"s6_{i}", gsr_variance_us2=0.0) for i in range(2)]
    a6 = audit_bio_surface(st6)
    tr.expect("ST-06: 2 rejected → CONTAMINATED",
          a6.surface_verdict, BioSurfaceVerdict.SURFACE_CONTAMINATED)

    # ST-07: threat_distribution accuracy
    st7 = (
        [_sig(f"s7a{i}", hardware_attested=True, anti_replay_passed=True) for i in range(300)]
        + [_sig(f"s7b{i}", gsr_variance_us2=0.0) for i in range(100)]
    )
    a7 = audit_bio_surface(st7)
    tr.expect("ST-07: PHYSIOLOGICAL_AUTHENTIC dist == 300",
          a7.threat_distribution[BioThreat.PHYSIOLOGICAL_AUTHENTIC.value], 300)
    tr.expect("ST-07b: GSR_FLATLINE dist == 100",
          a7.threat_distribution[BioThreat.GSR_FLATLINE.value], 100)

    # ST-08: high_severity_count threshold
    st8 = [_sig(f"s8_{i}", hrv_rmssd_ms=0.0) for i in range(3)]
    a8 = audit_bio_surface(st8)
    tr.expect("ST-08: high_sev == 3 → COMPROMISED",
          a8.surface_verdict, BioSurfaceVerdict.SURFACE_COMPROMISED)
    tr.expect("ST-08b: high_severity_count == 3", a8.high_severity_count, 3)

    # ST-09: HRV anomaly (not liveness) mass → all SUSPECT
    st9 = [_sig(f"s9_{i}", hrv_rmssd_ms=8.0) for i in range(200)]
    a9 = audit_bio_surface(st9)
    tr.expect("ST-09: 200 HRV anomaly → all SUSPECT", a9.suspect, 200)

    if tr.summary():
        raise SystemExit(1)


if __name__ == "__main__":
    _run_tests()
