#!/usr/bin/env python3
"""
option_space.py — a governor for the INTEGRITY of a decision's option set.

Every other decision tool here governs a decision once the options exist. This governs the part
that comes first and is the most quietly manipulated: WHICH options are on the table. Framing,
agenda-setting, a decoy option, and a silently-omitted "do nothing" rig a choice before anyone
evaluates anything.

WHAT IT DOES — and, crucially, WHAT IT REFUSES TO DO
It does NOT generate options and it does NOT claim the set is complete — you can never enumerate
the whole option space, and asserting you have is exactly the overclaim `goodhart_auditor` exists
to catch. It governs a *declared* set:

  - Pareto frontier      : surfaces the non-dominated options and REFUSES to collapse the
                           tradeoff into one blended score a chooser could game (the anti-Goodhart
                           move — no single seductive number, the tradeoffs stay visible).
  - decoy / dominated    : flags strictly-dominated options (they cannot be the rational best;
                           near a target they bias human choice — asymmetric dominance).
  - completeness flags    : is a "do nothing" baseline present? a reversible-minimal (low-regret)
                           option? is it a false choice (one real option vs a strawman)? are
                           declared option categories missing? (flags omissions; never asserts
                           the set is whole — the human owns the frame).
  - maturity              : grades each option's evidentiary footing (knowledge_maturity) and
                           flags when the most appealing option is the least-evidenced.
  - overclaim             : audits each option's declared metadata (goodhart_auditor).
  - non-self-approval     : the machine surfaces and ranks the frontier but CANNOT select. A
                           distinct human selects; the chosen option is what enters
                           governed_decision.

Deterministic, self-testing. Reuses knowledge_maturity and goodhart_auditor unchanged; the
selected option is shaped to hand straight to governed_decision.
Run:  python option_space.py
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple
import hashlib, json, os, sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)
import knowledge_maturity as km        # noqa: E402
import goodhart_auditor as ga          # noqa: E402


@dataclass(frozen=True)
class Criterion:
    """A decision criterion and its direction. maximize=False means lower is better (risk, cost)."""
    name: str
    maximize: bool = True


@dataclass(frozen=True)
class Option:
    """A single DECLARED option. No option is generated by this tool.

    id, label:     identity.
    criteria:      (criterion_name -> value) as declared; oriented via the Criterion set.
    reversible:    can the option be cleanly undone?
    scope:         containment vocabulary: minimal | bounded | broad | unbounded.
    evidence:      evidentiary footing for this option's projected outcomes (-> knowledge_maturity).
    category:      optional caller tag used for completeness checks (e.g. 'do_nothing').
    is_status_quo: marks the "do nothing" / baseline option.
    claims:        optional (field, backing) metadata audited for overclaim (-> goodhart_auditor).
    author:        who proposed it. NOT an authority.
    """
    id: str
    label: str
    criteria: Tuple[Tuple[str, float], ...]
    reversible: bool
    scope: str
    evidence: km.Evidence
    category: str = ""
    is_status_quo: bool = False
    claims: Tuple[Tuple[str, str], ...] = ()
    author: str = ""

    def val(self, name: str) -> Optional[float]:
        for k, v in self.criteria:
            if k == name:
                return v
        return None


@dataclass(frozen=True)
class OptionSpace:
    criteria: Tuple[Criterion, ...]
    options: Tuple[Option, ...]


@dataclass(frozen=True)
class SpaceReport:
    frontier: Tuple[str, ...]                       # non-dominated option ids
    dominated: Tuple[Tuple[str, str], ...]          # (option_id, dominated_by_id)
    per_criterion_leader: Tuple[Tuple[str, str], ...]  # (criterion, leading option id)
    maturity: Tuple[Tuple[str, str], ...]           # (option_id, maturity level name)
    integrity_flags: Tuple[str, ...]
    overclaim_flags: Tuple[str, ...]
    selected: Optional[str]                         # ALWAYS None from the machine
    note: str

    def to_dict(self) -> dict:
        return {"frontier": list(self.frontier),
                "dominated": [list(d) for d in self.dominated],
                "per_criterion_leader": [list(p) for p in self.per_criterion_leader],
                "maturity": [list(m) for m in self.maturity],
                "integrity_flags": list(self.integrity_flags),
                "overclaim_flags": list(self.overclaim_flags),
                "selected": self.selected, "note": self.note}

    def render(self) -> str:
        L = [f"FRONTIER (non-dominated): {', '.join(self.frontier) or '—'}"]
        if self.dominated:
            L.append("dominated (cannot be optimal; possible decoys): "
                     + ", ".join(f"{o}←{by}" for o, by in self.dominated))
        L.append("per-criterion leaders: "
                 + ", ".join(f"{c}:{o}" for c, o in self.per_criterion_leader))
        L.append("maturity: " + ", ".join(f"{o}:{m}" for o, m in self.maturity))
        for f in self.integrity_flags:
            L.append(f"  ⚑ {f}")
        for f in self.overclaim_flags:
            L.append(f"  ⚑ overclaim {f}")
        L.append(f"  » {self.note}")
        return "\n".join(L)


def _oriented(space: OptionSpace, opt: Option, crit: Criterion) -> Optional[float]:
    v = opt.val(crit.name)
    if v is None:
        return None
    return v if crit.maximize else -v


def _dominates(space: OptionSpace, a: Option, b: Option) -> bool:
    """a dominates b iff a is >= b on every criterion (oriented) and > on at least one.
    Missing values are treated fail-closed: a cannot dominate on a criterion it doesn't declare."""
    strictly_better_somewhere = False
    for c in space.criteria:
        av, bv = _oriented(space, a, c), _oriented(space, b, c)
        if av is None or bv is None:
            return False                     # incomparable on a missing criterion -> no domination
        if av < bv:
            return False
        if av > bv:
            strictly_better_somewhere = True
    return strictly_better_somewhere


def govern(space: OptionSpace, expected_categories: Tuple[str, ...] = ()) -> SpaceReport:
    """Govern the integrity of a declared option set. Deterministic; selects nothing."""
    opts = list(space.options)
    ids = [o.id for o in opts]

    # --- Pareto frontier + dominated (possible decoys) ---------------------------------
    dominated: List[Tuple[str, str]] = []
    frontier: List[str] = []
    for b in opts:
        dom_by = next((a.id for a in opts if a.id != b.id and _dominates(space, a, b)), None)
        if dom_by is not None:
            dominated.append((b.id, dom_by))
        else:
            frontier.append(b.id)

    # --- per-criterion leaders (keep tradeoffs explicit; no blended score) -------------
    leaders: List[Tuple[str, str]] = []
    for c in space.criteria:
        best_id, best_val = "", None
        for o in opts:
            ov = _oriented(space, o, c)
            if ov is None:
                continue
            if best_val is None or ov > best_val or (ov == best_val and o.id < best_id):
                best_val, best_id = ov, o.id
        leaders.append((c.name, best_id or "—"))

    # --- maturity per option ------------------------------------------------------------
    mat = {o.id: km.classify(o.evidence).level for o in opts}
    maturity = tuple((o.id, mat[o.id].name) for o in opts)

    # --- integrity flags ----------------------------------------------------------------
    flags: List[str] = []
    if not any(o.is_status_quo for o in opts):
        flags.append("no 'do nothing' / status-quo baseline in the set — "
                     "a decision cannot be judged against inaction")
    if not any(o.reversible and o.scope in ("minimal", "bounded") for o in opts):
        flags.append("no reversible, low-blast option — the set may force an "
                     "irreversible or over-broad choice")
    if all(not o.reversible for o in opts) and opts:
        flags.append("every option is irreversible — no recoverable path is offered")
    real = [o for o in opts if not o.is_status_quo and o.id in frontier]
    if len(real) <= 1:
        flags.append("false choice: at most one real (non-status-quo, non-dominated) option — "
                     "the alternatives are baselines or dominated fillers")
    if dominated:
        flags.append(f"{len(dominated)} strictly-dominated option(s) present "
                     "(cannot be the rational best; may act as decoys) — label or remove them")
    # missing declared categories (honest: driven by the caller's expectation, not a universal claim)
    present_cats = {o.category for o in opts if o.category}
    missing = [c for c in expected_categories if c not in present_cats]
    if missing:
        flags.append("declared option categories with no representative: "
                     + ", ".join(missing) + " — confirm the omission is intentional")
    # evidence asymmetry: an appealing (frontier) option is the least-evidenced
    if mat:
        best_mat = max(mat.values())
        thin_frontier = [oid for oid in frontier if mat[oid] == km.Maturity.ANECDOTE]
        if thin_frontier and best_mat >= km.Maturity.REPLICATED:
            flags.append("evidence asymmetry: frontier option(s) "
                         f"{', '.join(thin_frontier)} rest on ANECDOTE-level evidence while a "
                         "better-evidenced option exists — the appealing choice is the thin one")

    # --- overclaim audit on option metadata --------------------------------------------
    over: List[str] = []
    for o in opts:
        highs = [f for f in ga.audit([ga.Field(n, b) for n, b in o.claims])
                 if f.severity == "high"]
        for f in highs:
            over.append(f"{o.id}: {f.render()}")

    note = ("The machine surfaces the non-dominated frontier and the tradeoffs; it does NOT and "
            "CANNOT select, and it does not claim the set is complete. A distinct human chooses "
            "from the frontier (owning any omissions); the chosen option enters governed_decision.")
    return SpaceReport(tuple(frontier), tuple(dominated), tuple(leaders), maturity,
                       tuple(flags), tuple(over), None, note)


@dataclass(frozen=True)
class Selection:
    option_id: str
    human_id: str
    on_frontier: bool
    caveats: Tuple[str, ...]


class SelfApproval(Exception):
    """Raised when a non-human / the proposing author tries to select."""


def human_select(space: OptionSpace, report: SpaceReport, option_id: str,
                 human_id: str, author: str = "") -> Selection:
    """Record a HUMAN's selection from the space. Non-self-approval: the selector must be a
    distinct human (not empty, not 'auto'/'system', not the proposing author). A human MAY pick
    a dominated option, but the caveat is recorded rather than silently allowed."""
    hid = (human_id or "").strip()
    if not hid or hid.lower() in ("auto", "system") or hid.strip().lower() == author.strip().lower():
        raise SelfApproval("selection must be made by a distinct human, not the proposer or a system")
    if option_id not in {o.id for o in space.options}:
        raise ValueError(f"unknown option '{option_id}'")
    caveats: List[str] = []
    on_frontier = option_id in report.frontier
    if not on_frontier:
        caveats.append("selected option is DOMINATED — a strictly better option exists on the frontier")
    dict_mat = dict(report.maturity)
    if dict_mat.get(option_id) == km.Maturity.ANECDOTE.name:
        caveats.append("selected option rests on ANECDOTE-level evidence")
    return Selection(option_id, hid, on_frontier, tuple(caveats))


def fingerprint(report: SpaceReport) -> str:
    return hashlib.sha256(json.dumps(report.to_dict(), sort_keys=True).encode()).hexdigest()


# ---------------------------------------------------------------------------
# Demonstrations.
# ---------------------------------------------------------------------------
_CRIT = (Criterion("benefit", True), Criterion("risk", False), Criterion("cost", False))


def _ev(obs=6, methods=2, rep=True, adv=True):
    return km.Evidence(observation_count=obs, distinct_methods=methods,
                       independently_replicated=rep, adversarially_tested=adv)


def _healthy() -> OptionSpace:
    return OptionSpace(_CRIT, (
        Option("do_nothing", "Do nothing (baseline)",
               (("benefit", 0.0), ("risk", 0.1), ("cost", 0.0)), True, "minimal",
               _ev(), category="do_nothing", is_status_quo=True),
        Option("pilot", "Reversible 5% pilot",
               (("benefit", 5.0), ("risk", 2.0), ("cost", 3.0)), True, "minimal",
               _ev(), category="reversible_pilot"),
        Option("rollout", "Full irreversible rollout",
               (("benefit", 9.0), ("risk", 6.0), ("cost", 8.0)), False, "broad",
               _ev(), category="full_commit"),
    ))


def _rigged() -> OptionSpace:
    return OptionSpace(_CRIT, (
        Option("our_plan", "Our plan (the target)",
               (("benefit", 7.0), ("risk", 3.0), ("cost", 4.0)), False, "broad",
               _ev(), category="full_commit",
               claims=(("recommended_verified", "assumed"),)),   # overclaim: 'verified' unbacked
        Option("decoy", "A worse-on-everything option",
               (("benefit", 5.0), ("risk", 5.0), ("cost", 6.0)), False, "broad",
               _ev(), category="full_commit"),                   # strictly dominated by our_plan
    ))


def _asymmetric() -> OptionSpace:
    return OptionSpace(_CRIT, (
        Option("aggressive", "Aggressive, thinly-evidenced",
               (("benefit", 10.0), ("risk", 8.0), ("cost", 9.0)), False, "broad",
               km.Evidence(observation_count=1), category="full_commit"),   # ANECDOTE
        Option("safe", "Conservative, well-evidenced",
               (("benefit", 4.0), ("risk", 1.0), ("cost", 2.0)), True, "minimal",
               _ev(), category="reversible_pilot", is_status_quo=False),
        Option("do_nothing", "Do nothing", (("benefit", 0.0), ("risk", 0.1), ("cost", 0.0)),
               True, "minimal", _ev(), category="do_nothing", is_status_quo=True),
    ))


def _cases():
    return {"healthy set": (_healthy(), ("do_nothing", "reversible_pilot", "full_commit")),
            "rigged set (no baseline, a decoy, an overclaim)":
                (_rigged(), ("do_nothing", "reversible_pilot", "full_commit")),
            "evidence-asymmetric set": (_asymmetric(), ())}


def _self_test() -> None:
    # 1. healthy: all three non-dominated, few/no integrity flags, nothing dominated
    r = govern(*_cases()["healthy set"])
    assert set(r.frontier) == {"do_nothing", "pilot", "rollout"}
    assert r.dominated == ()
    assert r.selected is None                                   # machine never selects
    assert not any("false choice" in f for f in r.integrity_flags)

    # 2. rigged: decoy is dominated, baseline missing flagged, false-choice flagged, overclaim caught
    r = govern(*_cases()["rigged set (no baseline, a decoy, an overclaim)"])
    assert ("decoy", "our_plan") in r.dominated
    assert any("do nothing" in f for f in r.integrity_flags)
    assert any("false choice" in f for f in r.integrity_flags)
    assert any("recommended_verified" in f for f in r.overclaim_flags)

    # 3. asymmetry: the appealing frontier option is the ANECDOTE one -> flagged
    r = govern(*_cases()["evidence-asymmetric set"])
    assert "aggressive" in r.frontier
    assert any("evidence asymmetry" in f for f in r.integrity_flags)

    # 4. non-self-approval: the proposer / a system cannot select; a human can
    space, cats = _cases()["healthy set"]
    rep = govern(space, cats)
    try:
        human_select(space, rep, "pilot", human_id="", author="agent")
        assert False, "empty selector must raise"
    except SelfApproval:
        pass
    try:
        human_select(space, rep, "pilot", human_id="agent", author="agent")
        assert False, "self-approval must raise"
    except SelfApproval:
        pass
    sel = human_select(space, rep, "pilot", human_id="human:owner", author="agent")
    assert sel.option_id == "pilot" and sel.on_frontier and not sel.caveats

    # selecting a dominated option is allowed but caveated
    space2, cats2 = _cases()["rigged set (no baseline, a decoy, an overclaim)"]
    rep2 = govern(space2, cats2)
    sel2 = human_select(space2, rep2, "decoy", human_id="human:owner", author="agent")
    assert not sel2.on_frontier and any("DOMINATED" in c for c in sel2.caveats)

    # determinism
    assert fingerprint(govern(*_cases()["healthy set"])) == fingerprint(govern(*_cases()["healthy set"]))
    print("self-test passed")


if __name__ == "__main__":
    _self_test()
    print("\n--- option-set integrity governor (surfaces the frontier; never selects) ---\n")
    for name, (space, cats) in _cases().items():
        print(f"# {name}")
        rep = govern(space, cats)
        print(rep.render())
        print(f"  fingerprint {fingerprint(rep)[:16]} …\n")
    # closing the loop: a human selects; the chosen option is what would enter governed_decision
    space, cats = _cases()["healthy set"]
    rep = govern(space, cats)
    sel = human_select(space, rep, "pilot", human_id="human:owner", author="agent")
    print(f"# human selection -> {sel.option_id} by {sel.human_id} "
          f"(on frontier: {sel.on_frontier}) -> hand to governed_decision")
